module.exports.continentDataField = [
  "no.",
  "name",
  "cases",
  "newCases",
  "deaths",
  "newDeaths",
  "recovered",
  "newRecovered",
  "activeCases",
  "seriousCases",
];

module.exports.countryDataField = [
  "no.",
  "name",
  "cases",
  "newCases",
  "deaths",
  "newDeaths",
  "recovered",
  "newRecovered",
  "activeCases",
  "seriousCases",
  "totalsPerMillion",
  "deathsPerMillion",
  "tests",
  "testsPerMillion",
  "population",
  "continent",
  "oneCasePerXPeople",
  "oneDeathPerXPeople",
  "oneTestPerXPeople",
];
